// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://johwvrqiuwezpmosnvyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaHd2cnFpdXdlenBtb3NudnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4OTAwNzcsImV4cCI6MjA2MTQ2NjA3N30.-d6r0aIFYMlDrYIA5VOVau-oMy10DDGDSELvY_AyiFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);